### ISSUE TITLE
Cannot create 20 or more subGroups

### ISSUE THREAD

**Issue by alviss7** [adorsys/keycloak-config-cli#1014]
### Current Behavior

Cannot create 20 or more subGroups

```
java.lang.IllegalStateException: Failed to execute CommandLineRunner
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:771)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:752)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292)
        at de.adorsys.keycloak.config.KeycloakConfigApplication.main(KeycloakConfigApplication.java:35)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
Caused by: java.lang.NullPointerException: Cannot invoke "org.keycloak.representations.idm.GroupRepresentation.getRealmRoles()" because "existingGroup" is null
        at de.adorsys.keycloak.config.service.GroupImportService.addRealmRoles(GroupImportService.java:175)
        at de.adorsys.keycloak.config.service.GroupImportService.addSubGroup(GroupImportService.java:213)
        at de.adorsys.keycloak.config.service.GroupImportService.addSubGroups(GroupImportService.java:202)
        at de.adorsys.keycloak.config.service.GroupImportService.createGroup(GroupImportService.java:151)
        at de.adorsys.keycloak.config.service.GroupImportService.createOrUpdateRealmGroup(GroupImportService.java:139)
        at de.adorsys.keycloak.config.service.GroupImportService.lambda$createOrUpdateGroups$0(GroupImportService.java:77)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at de.adorsys.keycloak.config.service.GroupImportService.createOrUpdateGroups(GroupImportService.java:81)
        at de.adorsys.keycloak.config.service.GroupImportService.importGroups(GroupImportService.java:69)
        at de.adorsys.keycloak.config.service.RealmImportService.configureRealm(RealmImportService.java:203)
        at de.adorsys.keycloak.config.service.RealmImportService.updateRealm(RealmImportService.java:195)
        at de.adorsys.keycloak.config.service.RealmImportService.updateRealmIfNecessary(RealmImportService.java:153)
        at de.adorsys.keycloak.config.service.RealmImportService.doImport(RealmImportService.java:144)
        at de.adorsys.keycloak.config.KeycloakConfigRunner.run(KeycloakConfigRunner.java:79)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:768)
        ... 13 common frames omitted
```

### Expected Behavior

Create more than 20 subGroups, divided into one or more groups

### Steps To Reproduce

With this config :
```markdown
id: master
realm: master
displayName: Keycloak
enabled: true
userManagedAccessAllowed: true
eventsEnabled: true
adminEventsEnabled: true
rememberMe: true
bruteForceProtected: true
failureFactor: 5
internationalizationEnabled: true
passwordPolicy: "length(8) and specialChars(1) and upperCase(1) and lowerCase(1) and digits(1)"
supportedLocales:
- en
- fr
- es

groups:
- name: group
  subGroups:
    - name: group1
    - name: group2
    - name: group3
    - name: group4
    - name: group5
    - name: group6
    - name: group7
    - name: group8
    - name: group9
    - name: group10
    - name: group11
    - name: group12
    - name: group13
    - name: group14
    - name: group15
    - name: group16
    - name: group17
    - name: group18
    - name: group19
    - name: group20
    - name: group21
    - name: group22
    - name: group23
    - name: group24
    - name: group25
    - name: group26
```

And run java -jar keycloak-config-cli.jar

### Environment

- Keycloak Version: 24.0.3
- keycloak-config-cli Version: 5.12.0
- Java Version: 17

**Comment by timadevelop** [comment]
I'm not that familiar with KC Java API but I got the same issue with >10 groups and it seems to be caused by 

https://github.com/keycloak/keycloak/blame/69497382d8cc6c622e815184d9bc27cb0dc6a400/services/src/main/java/org/keycloak/services/resources/admin/GroupResource.java#L161 / https://github.com/keycloak/keycloak/blob/ece72cd491b68422940136bc6171392e07db6679/services/src/main/java/org/keycloak/services/resources/admin/GroupResource.java#L172

used in 

https://github.com/adorsys/keycloak-config-cli/blob/1ce036ec029afc93c4e614ec1278afb6b77de7b3/src/main/java/de/adorsys/keycloak/config/repository/GroupRepository.java#L122

and 

https://github.com/adorsys/keycloak-config-cli/blob/1ce036ec029afc93c4e614ec1278afb6b77de7b3/src/test/java/de/adorsys/keycloak/config/test/util/SubGroupUtil.java#L44


@jonasvoelcker @st3v0rr Does it make sense to use something like `.getSubGroups(null, group.getSubGroupCount(), false);` instead?

**Comment by jonasvoelcker** [comment]
> I'm not that familiar with KC Java API but I got the same issue with >10 groups and it seems to be caused by
> 
> https://github.com/keycloak/keycloak/blame/69497382d8cc6c622e815184d9bc27cb0dc6a400/services/src/main/java/org/keycloak/services/resources/admin/GroupResource.java#L161 / https://github.com/keycloak/keycloak/blob/ece72cd491b68422940136bc6171392e07db6679/services/src/main/java/org/keycloak/services/resources/admin/GroupResource.java#L172
> 
> used in
> 
> https://github.com/adorsys/keycloak-config-cli/blob/1ce036ec029afc93c4e614ec1278afb6b77de7b3/src/main/java/de/adorsys/keycloak/config/repository/GroupRepository.java#L122
> 
> and
> 
> https://github.com/adorsys/keycloak-config-cli/blob/1ce036ec029afc93c4e614ec1278afb6b77de7b3/src/test/java/de/adorsys/keycloak/config/test/util/SubGroupUtil.java#L44
> 
> @jonasvoelcker @st3v0rr Does it make sense to use something like `.getSubGroups(null, group.getSubGroupCount(), false);` instead?

Sorry for not responding. Integer.MAX_VALUE seems to be the perfect way. I've added some comment to your PR, please stay on the topic :)
