### ISSUE TITLE
Parallel import: ClassNotFoundException: org.jboss.resteasy.client.jaxrs.internal.proxy.ProxyBuilderImpl

### ISSUE THREAD

**Issue by gim-** [adorsys/keycloak-config-cli#1107]
### Current Behavior

When I add `--import.parallel=true` argument, the keycloak-config-cli fails right at the start.

Command example:
```bash
java -jar keycloak-config-cli-22.0.4.jar  --import.cache.enabled=false --import.parallel=true \
  --keycloak.url='http://localhost:8080' \
  --keycloak.user='admin' \
  --keycloak.password='admin' \
  --import.files.locations='./config/*' \
  --import.var-substitution.enabled='true'
```

Output:
```
2024-07-18T13:02:36.198+03:00  INFO 22864 --- [           main] d.a.k.config.KeycloakConfigRunner        : keycloak-config-cli ran in 00:00.985.
2024-07-18T13:02:36.200+03:00  INFO 22864 --- [           main] .s.b.a.l.ConditionEvaluationReportLogger :

Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2024-07-18T13:02:36.219+03:00 ERROR 22864 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.RuntimeException: java.lang.RuntimeException: java.lang.ClassNotFoundException: org.jboss.resteasy.client.jaxrs.internal.proxy.ProxyBuilderImpl
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
        at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:540)
        at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:567)
        at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:670)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:765)
        at de.adorsys.keycloak.config.service.ClientScopeImportService.createOrUpdateClientScopes(ClientScopeImportService.java:173)
        at de.adorsys.keycloak.config.service.ClientScopeImportService.doImport(ClientScopeImportService.java:65)
        at de.adorsys.keycloak.config.service.RealmImportService.configureRealm(RealmImportService.java:200)
        at de.adorsys.keycloak.config.service.RealmImportService.updateRealm(RealmImportService.java:196)
        at de.adorsys.keycloak.config.service.RealmImportService.updateRealmIfNecessary(RealmImportService.java:154)
        at de.adorsys.keycloak.config.service.RealmImportService.doImport(RealmImportService.java:145)
        at de.adorsys.keycloak.config.KeycloakConfigRunner.run(KeycloakConfigRunner.java:79)
        at org.springframework.boot.SpringApplication.lambda$callRunner$5(SpringApplication.java:790)
        at org.springframework.util.function.ThrowingConsumer$1.acceptWithException(ThrowingConsumer.java:83)
        at org.springframework.util.function.ThrowingConsumer.accept(ThrowingConsumer.java:60)
        at org.springframework.util.function.ThrowingConsumer$1.accept(ThrowingConsumer.java:88)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:798)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:789)
        at org.springframework.boot.SpringApplication.lambda$callRunners$3(SpringApplication.java:774)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:774)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:341)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1354)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343)
        at de.adorsys.keycloak.config.KeycloakConfigApplication.main(KeycloakConfigApplication.java:35)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:91)
        at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:53)
        at org.springframework.boot.loader.launch.PropertiesLauncher.main(PropertiesLauncher.java:574)
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: org.jboss.resteasy.client.jaxrs.internal.proxy.ProxyBuilderImpl
        at org.jboss.resteasy.client.jaxrs.ProxyBuilder.builder(ProxyBuilder.java:36)
        at org.jboss.resteasy.client.jaxrs.internal.ClientWebTarget.createProxyBuilder(ClientWebTarget.java:99)
        at org.jboss.resteasy.client.jaxrs.internal.ClientWebTarget.proxy(ClientWebTarget.java:87)
        at org.keycloak.admin.client.spi.ResteasyClientClassicProvider.targetProxy(ResteasyClientClassicProvider.java:48)
        at org.keycloak.admin.client.Keycloak.realms(Keycloak.java:142)
        at de.adorsys.keycloak.config.repository.RealmRepository.getResource(RealmRepository.java:56)
        at de.adorsys.keycloak.config.repository.ClientScopeRepository.searchByName(ClientScopeRepository.java:161)
        at de.adorsys.keycloak.config.service.ClientScopeImportService.createOrUpdateClientScope(ClientScopeImportService.java:219)
        at de.adorsys.keycloak.config.service.ClientScopeImportService.lambda$createOrUpdateClientScopes$0(ClientScopeImportService.java:171)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
        at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Caused by: java.lang.ClassNotFoundException: org.jboss.resteasy.client.jaxrs.internal.proxy.ProxyBuilderImpl
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
        at org.jboss.resteasy.client.jaxrs.ProxyBuilder.builder(ProxyBuilder.java:32)
        ... 18 common frames omitted
```

### Expected Behavior

Successfully import resources in parallel.

### Steps To Reproduce

```markdown
1. Download `keycloak-config-cli-22.0.4.jar` from the latest v6.1.5 release page on GitHub
2. Run the tool with `--import.parallel=true`
3. See the error
```

### Environment

- Keycloak Version: 22.0.11.redhat-00001
- keycloak-config-cli Version: v6.1.5
- Java Version: 21

**Comment by gim-** [comment]
Hi @Motouom 

Do you mean the [v6.1.6](https://github.com/adorsys/keycloak-config-cli/releases/tag/v6.1.6) commit tag is the latest release that fixes this? Or do you mean the main branch HEAD?

**Comment by Motouom** [comment]
Hello @gim-

Thanks for your response. It works with version 6.1.6.

**Comment by gim-** [comment]
@Motouom I finally tried it today and it doesn't seem to work in the latest release (6.3.0)

Keycloak:
```shell
docker run -d --name keycloak -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak:26.0 start-dev
```

Command:
```shell
java -jar keycloak-config-cli-26.0.5.jar --import.files.locations=realm-export.json --keycloak.url=http://localhost:8080 --keycloak.user=admin --keycloak.password=admin --import.parallel=true
```

Output:
```
2025-02-05T17:24:55.522+02:00  INFO 60573 --- [           main] d.a.k.config.KeycloakConfigApplication   : Starting KeycloakConfigApplication v6.3.0 using Java 21.0.5 with PID 60573 (/Users/andrejs.mivreniks/IdeaProjects/playground/keycloak-config-cli-26.0.5.jar started by andrejs.mivreniks in /Users/andrejs.mivreniks/IdeaProjects/playground)
2025-02-05T17:24:55.525+02:00  INFO 60573 --- [           main] d.a.k.config.KeycloakConfigApplication   : No active profile set, falling back to 1 default profile: "default"
2025-02-05T17:24:55.781+02:00  INFO 60573 --- [           main] d.a.k.config.KeycloakConfigApplication   : Started KeycloakConfigApplication in 0.488 seconds (process running for 0.732)
2025-02-05T17:24:56.101+02:00  INFO 60573 --- [           main] d.a.k.config.KeycloakConfigRunner        : Importing file 'file:realm-export.json'
2025-02-05T17:24:56.918+02:00 ERROR 60573 --- [           main] d.a.k.config.KeycloakConfigRunner        : java.lang.RuntimeException: java.lang.ClassNotFoundException: org.jboss.resteasy.client.jaxrs.internal.proxy.ProxyBuilderImpl
2025-02-05T17:24:56.919+02:00  INFO 60573 --- [           main] d.a.k.config.KeycloakConfigRunner        : keycloak-config-cli ran in 00:00.936.
```

**realm-export.json** contains just regular Keycloak export of a newly created realm.

**Comment by gim-** [comment]
@Motouom I started Keycloak 25.0.1 and created a build from [v6.1.6](https://github.com/adorsys/keycloak-config-cli/releases/tag/v6.1.6) tag - same issue

**Comment by Motouom** [comment]
@gim- Hello. i tried again and it is working. i don't know why it disturbs for you or doesn't work. here is `v25.0.1` for keycloak and `v6.1.6` for kccli.


starting the keycloak console
```
 keycloak-config-cli git:(v6.1.6) ✗ docker run -d --name keycloak \
    -e KEYCLOAK_ADMIN=admin \
    -e KEYCLOAK_ADMIN_PASSWORD=admin \
    -p 8080:8080 \
    quay.io/keycloak/keycloak:25.0.1  start-dev
```

applying the config

```
keycloak-config-cli git:(v6.1.6) ✗ java -jar ./target/keycloak-config-cli.jar \
    --keycloak.url=http://localhost:8080 \
    --keycloak.ssl-verify=true \
    --keycloak.user=admin \
    --keycloak.password=admin \ --import.parallel=true \ --import.enabled=false \
    --import.files.locations=./contrib/example-config/moped.json
2025-02-06T08:12:46.760+01:00  INFO 750945 --- [           main] d.a.k.config.KeycloakConfigApplication   : Starting KeycloakConfigApplication v6.1.6 using Java 21.0.5 with PID 750945 (/home/victoire/Desktop/keycloak-config-cli/target/keycloak-config-cli.jar started by victoire in /home/victoire/Desktop/keycloak-config-cli)
2025-02-06T08:12:46.767+01:00  INFO 750945 --- [           main] d.a.k.config.KeycloakConfigApplication   : No active profile set, falling back to 1 default profile: "default"
2025-02-06T08:12:47.432+01:00  INFO 750945 --- [           main] d.a.k.config.KeycloakConfigApplication   : Started KeycloakConfigApplication in 1.397 seconds (process running for 1.853)
2025-02-06T08:12:48.266+01:00  INFO 750945 --- [           main] d.a.k.config.KeycloakConfigRunner        : Importing file 'file:contrib/example-config/moped.json'
2025-02-06T08:12:54.929+01:00  INFO 750945 --- [           main] d.a.k.config.KeycloakConfigRunner        : keycloak-config-cli ran in 00:06.976.
```

**Comment by gim-** [comment]
@Motouom Ok, I see what's going on. It only works if you execute a jar from the project directory, it probably picks up external classes. If you move that jar to a different directory, or cd to a different dir, it won't work. Also, make sure the realm is deleted before you run it.

```
  % pwd
/Users/user/IdeaProjects/playground

  % java -jar ../keycloak-config-cli/target/keycloak-config-cli.jar --import.files.locations=realm-export.json --keycloak.url=http://localhost:8080 --keycloak.user=admin --keycloak.password=admin --import.parallel=true
2025-02-06T10:47:03.624+02:00  INFO 73781 --- [           main] d.a.k.config.KeycloakConfigApplication   : Starting KeycloakConfigApplication v6.1.6 using Java 21.0.5 with PID 73781 (/Users/user/IdeaProjects/keycloak-config-cli/target/keycloak-config-cli.jar started by user in /Users/user/IdeaProjects/playground)
2025-02-06T10:47:03.626+02:00  INFO 73781 --- [           main] d.a.k.config.KeycloakConfigApplication   : No active profile set, falling back to 1 default profile: "default"
2025-02-06T10:47:03.869+02:00  INFO 73781 --- [           main] d.a.k.config.KeycloakConfigApplication   : Started KeycloakConfigApplication in 0.461 seconds (process running for 0.666)
2025-02-06T10:47:04.176+02:00  INFO 73781 --- [           main] d.a.k.config.KeycloakConfigRunner        : Importing file 'file:realm-export.json'
2025-02-06T10:47:04.511+02:00 ERROR 73781 --- [           main] d.a.k.config.KeycloakConfigRunner        : java.lang.RuntimeException: java.lang.ClassNotFoundException: org.jboss.resteasy.client.jaxrs.internal.proxy.ProxyBuilderImpl
2025-02-06T10:47:04.511+02:00  INFO 73781 --- [           main] d.a.k.config.KeycloakConfigRunner        : keycloak-config-cli ran in 00:00.451.

  % cd ../keycloak-config-cli/

  % java -jar ./target/keycloak-config-cli.jar \
            --keycloak.url=http://localhost:8080 \
            --keycloak.user=admin \
            --keycloak.password=admin \ --import.parallel=true --import.files.locations=../playground/realm-export.json
2025-02-06T10:47:23.958+02:00  INFO 73820 --- [           main] d.a.k.config.KeycloakConfigApplication   : Starting KeycloakConfigApplication v6.1.6 using Java 21.0.5 with PID 73820 (/Users/user/IdeaProjects/keycloak-config-cli/target/keycloak-config-cli.jar started by user in /Users/user/IdeaProjects/keycloak-config-cli)
2025-02-06T10:47:23.960+02:00  INFO 73820 --- [           main] d.a.k.config.KeycloakConfigApplication   : No active profile set, falling back to 1 default profile: "default"
2025-02-06T10:47:24.205+02:00  INFO 73820 --- [           main] d.a.k.config.KeycloakConfigApplication   : Started KeycloakConfigApplication in 0.461 seconds (process running for 0.668)
2025-02-06T10:47:24.509+02:00  INFO 73820 --- [           main] d.a.k.config.KeycloakConfigRunner        : Importing file 'file:../playground/realm-export.json'
2025-02-06T10:47:25.967+02:00  INFO 73820 --- [           main] d.a.k.config.KeycloakConfigRunner        : keycloak-config-cli ran in 00:01.578.
```

**Comment by Motouom** [comment]
Okay @gim- 


So if it works fine fine, I guess it's just maven doing it's thing 😅


So it works right?

**Comment by gim-** [comment]
@Motouom No, not really. It's an uber-jar and it makes sense to expect it to work independantly. There's either dependency version conflict or somehow Maven is not copying all dependencies into an uber-jar.

**Comment by adhurjaty** [comment]
I am also running into this issue when running from docker (locally and in CI). Running the following command locally
```
docker run \
-e KEYCLOAK_URL="http://host.docker.internal:8080/" \
-e KEYCLOAK_USER="<admin>" \
-e KEYCLOAK_PASSWORD="<admin>" \
-e KEYCLOAK_AVAILABILITYCHECK_ENABLED=true \
-e KEYCLOAK_AVAILABILITYCHECK_TIMEOUT=120s \
-e IMPORT_FILES_LOCATIONS="..." \
-e IMPORT_PARALLEL=true \
-v /path/to/config:/config \
adorsys/keycloak-config-cli:latest-25.0.1
```

**Comment by Motouom** [comment]
Thank you Very much @adhurjaty  for the helping hand.


I will review the PR ASAP

**Comment by Motouom** [comment]
Hello @adhurjaty  i left a comment on the PR. 

Thanks for the helping hand
