### ISSUE TITLE
Force continue on conflict

### ISSUE THREAD

**Issue by todeb** [adorsys/keycloak-config-cli#315]
Hi,

when specified ldap user federatiion and then try to add user with the same name I receive the conflict, which is ok. But the tool stopping processsing futher configuration lines. Expected is to continue of processing for other users and configuration after conflict.

Also additional log which configuration line is causing conflict, or some more details what cannot be imported might be usefull.

```
2021-02-09 12:39:21.219 ERROR 977 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:807) [spring-boot-2.4.2.jar!/:2.4.2]
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:788) [spring-boot-2.4.2.jar!/:2.4.2]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:333) [spring-boot-2.4.2.jar!/:2.4.2]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1311) [spring-boot-2.4.2.jar!/:2.4.2]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300) [spring-boot-2.4.2.jar!/:2.4.2]
        at de.adorsys.keycloak.config.KeycloakConfigApplication.main(KeycloakConfigApplication.java:35) [classes!/:3.0.0]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_272]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_272]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_272]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_272]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [keycloak-config-cli-10.0.2.jar:3.0.0]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:107) [keycloak-config-cli-10.0.2.jar:3.0.0]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [keycloak-config-cli-10.0.2.jar:3.0.0]
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467) [keycloak-config-cli-10.0.2.jar:3.0.0]
Caused by: javax.ws.rs.ClientErrorException: HTTP 409 Conflict
        at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.handleErrorStatus(ClientInvocation.java:284) ~[resteasy-client-4.6.0.Final.jar!/:4.6.0.Final]
        at org.jboss.resteasy.client.jaxrs.internal.proxy.extractors.DefaultEntityExtractorFactory$3.extractEntity(DefaultEntityExtractorFactory.java:50) ~[resteasy-client-4.6.0.Final.jar!/:4.6.0.Final]
        at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:154) ~[resteasy-client-4.6.0.Final.jar!/:4.6.0.Final]
        at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:115) ~[resteasy-client-4.6.0.Final.jar!/:4.6.0.Final]
        at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76) ~[resteasy-client-4.6.0.Final.jar!/:4.6.0.Final]
        at com.sun.proxy.$Proxy87.update(Unknown Source) ~[na:na]
        at de.adorsys.keycloak.config.repository.UserRepository.updateUser(UserRepository.java:106) ~[classes!/:3.0.0]
        at de.adorsys.keycloak.config.service.UserImportService$UserImport.updateUser(UserImportService.java:140) ~[classes!/:3.0.0]
        at de.adorsys.keycloak.config.service.UserImportService$UserImport.importUser(UserImportService.java:121) ~[classes!/:3.0.0]
        at de.adorsys.keycloak.config.service.UserImportService.importUser(UserImportService.java:91) ~[classes!/:3.0.0]
        at de.adorsys.keycloak.config.service.UserImportService.lambda$doImport$0(UserImportService.java:81) ~[classes!/:3.0.0]
        at java.util.ArrayList.forEach(ArrayList.java:1259) ~[na:1.8.0_272]
        at de.adorsys.keycloak.config.service.UserImportService.doImport(UserImportService.java:85) ~[classes!/:3.0.0]
        at de.adorsys.keycloak.config.service.RealmImportService.configureRealm(RealmImportService.java:177) ~[classes!/:3.0.0]
        at de.adorsys.keycloak.config.service.RealmImportService.updateRealm(RealmImportService.java:167) ~[classes!/:3.0.0]
        at de.adorsys.keycloak.config.service.RealmImportService.updateRealmIfNecessary(RealmImportService.java:142) ~[classes!/:3.0.0]
        at de.adorsys.keycloak.config.service.RealmImportService.doImport(RealmImportService.java:132) ~[classes!/:3.0.0]
        at de.adorsys.keycloak.config.KeycloakConfigRunner.run(KeycloakConfigRunner.java:70) ~[classes!/:3.0.0]
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:804) [spring-boot-2.4.2.jar!/:2.4.2]
        ... 13 common frames omitted
```

**Comment by jkroepke** [comment]
The questions is, why it's okay to ignore an error?

**Comment by todeb** [comment]
I do not want to ignore it entirely, the warning about conflict should be enough, that can be fixed afterwards and not blocking entire importing. It might be also beneficial in testing configuration, so by one run, you will already see all the issues. Maybe --force parameter should allow this or setting up additional one.

**Comment by jkroepke** [comment]
> the warning about conflict should be enough
I disagree.

If Keycloak returns a client side error (HTTP 409), I wouldn't like to go in general report errors as warning. Instead that, users should fix the imports. There is not reason to allow not working import files by suppress errors.

You could have multiple import files each realm. If you want to test a realm config, extract the users to a different import file and run the users import file only on your test environment.

>  so by one run, you will already see all the issues. 

And a lot of false positives. Like, if the creation of a group failed, creating a users with such a group will fail, too.
