### ISSUE TITLE
Removal of (referenced) clientScope causes 400 Bad Request

### ISSUE THREAD

**Issue by chlumper** [adorsys/keycloak-config-cli#349]
**Describe the bug**
Removal of `clientScope` causes `HTTP 400 Bad Request` if the scope is referenced by a `client` at `defaultClientScopes` although it should be removed from the `defaultClientScopes` as well based on the import file ("invalid order of deletion").

**To Reproduce**

- <details><summary>Create scope <code>my-scope</code> and client <code>my-client</code> which references it at <code>defaultClientScopes</code> [click to expand]</summary>

  JSON (`realm-node.json`):
  ```json
  {
    "realm": "mynode",
    "displayName": "mynode",
    "clients": [
      {
        "clientId": "my-client",
        "name": "My Client",
        "defaultClientScopes": [
          "web-origins",
          "role_list",
          "roles",
          "profile",
          "email",
          "my-scope"
        ]
      }
    ],
    "clientScopes": [
      {
        "name": "my-scope",
        "description": "My Scope",
        "protocol": "openid-connect",
        "attributes": {
          "include.in.token.scope": "true",
          "display.on.consent.screen": "true",
          "consent.screen.text": "My Scope"
        }
      }
    ],
    "keycloakVersion": "12.0.4"
  }
  ```
  CMD:
  ```bash
  docker run -it --rm -e KEYCLOAK_URL=http://localhost:8080/auth -e KEYCLOAK_USER=admin -e KEYCLOAK_PASSWORD=<my-admin-pw> -e KEYCLOAK_GRANTTYPE=password -e IMPORT_PATH=/config/realm-node.json -e SPRING_PROFILES_INCLUDE=debug -v ./config:/config adorsys/keycloak-config-cli:latest-12.0.4
  ```
</details>

- <details><summary>Try to remove scope <code>my-scope</code> and reference of scope at <code>defaultClientScopes</code> of client <code>my-client</code> at subsequent import [click to expand]</summary>

  JSON (`realm-node.json`):
  ```json
  {
    "realm": "mynode",
    "displayName": "mynode",
    "clients": [
      {
        "clientId": "my-client",
        "name": "My Client",
        "defaultClientScopes": [
          "web-origins",
          "role_list",
          "roles",
          "profile",
          "email"
        ]
      }
    ],
    "clientScopes": [
    ],
    "keycloakVersion": "12.0.4"
  }
  ```
  CMD:
  ```bash
  docker run -it --rm -e KEYCLOAK_URL=http://localhost:8080/auth -e KEYCLOAK_USER=admin -e KEYCLOAK_PASSWORD=<my-admin-pw> -e KEYCLOAK_GRANTTYPE=password -e IMPORT_PATH=/config/realm-node.json -e SPRING_PROFILES_INCLUDE=debug -v ./config:/config adorsys/keycloak-config-cli:latest-12.0.4
  ```
</details>

- Causes the following error:

  ```log
  INFO 1 --- [main] d.a.k.config.KeycloakConfigApplication   : Starting KeycloakConfigApplication v3.1.2-rc0 using Java 11.0.10 on c5577316aa7b with PID 1 (/opt/keycloak-config-cli.jar started by ? in /)
  INFO 1 --- [main] d.a.k.config.KeycloakConfigApplication   : The following profiles are active: debug
  INFO 1 --- [main] d.a.k.config.KeycloakConfigApplication   : Started KeycloakConfigApplication in 1.156 seconds (JVM running for 1.6)
  INFO 1 --- [main] d.a.k.config.KeycloakConfigRunner        : Importing file '/config/realm-node.json'
  INFO 1 --- [main] d.a.k.config.provider.KeycloakProvider   : Wait 60 seconds until http://localhost:8080/auth is available ...
  DEBUG 1 --- [main] d.a.k.config.service.RealmImportService  : Updating realm 'mynode'...
  DEBUG 1 --- [main] d.a.k.c.s.ClientScopeImportService       : Delete clientScope 'my-scope' in realm 'mynode'
  ERROR 1 --- [main] d.a.k.config.KeycloakConfigRunner        : HTTP 400 Bad Request
  INFO 1 --- [main] d.a.k.config.KeycloakConfigRunner        : keycloak-config-cli running in 00:01.329.
  ```
  <details><summary>Stack-Trace [click to expand]</summary>

  ```log
  ERROR 1 --- [main] o.s.boot.SpringApplication               : Application run failed

  java.lang.IllegalStateException: Failed to execute CommandLineRunner
          at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:807) ~[spring-boot-2.4.3.jar!/:2.4.3]
          at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:788) ~[spring-boot-2.4.3.jar!/:2.4.3]
          at org.springframework.boot.SpringApplication.run(SpringApplication.java:333) ~[spring-boot-2.4.3.jar!/:2.4.3]
          at org.springframework.boot.SpringApplication.run(SpringApplication.java:1311) ~[spring-boot-2.4.3.jar!/:2.4.3]
          at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300) ~[spring-boot-2.4.3.jar!/:2.4.3]
          at de.adorsys.keycloak.config.KeycloakConfigApplication.main(KeycloakConfigApplication.java:35) ~[classes!/:3.1.2-rc0]
          at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
          at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
          at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
          at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
          at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[keycloak-config-cli.jar:3.1.2-rc0]
          at org.springframework.boot.loader.Launcher.launch(Launcher.java:107) ~[keycloak-config-cli.jar:3.1.2-rc0]
          at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[keycloak-config-cli.jar:3.1.2-rc0]
          at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467) ~[keycloak-config-cli.jar:3.1.2-rc0]
  Caused by: javax.ws.rs.BadRequestException: HTTP 400 Bad Request
          at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.handleErrorStatus(ClientInvocation.java:262) ~[resteasy-client-4.6.0.Final.jar!/:4.6.0.Final]
          at org.jboss.resteasy.client.jaxrs.internal.proxy.extractors.DefaultEntityExtractorFactory$3.extractEntity(DefaultEntityExtractorFactory.java:50) ~[resteasy-client-4.6.0.Final.jar!/:4.6.0.Final]
          at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:154) ~[resteasy-client-4.6.0.Final.jar!/:4.6.0.Final]
          at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:115) ~[resteasy-client-4.6.0.Final.jar!/:4.6.0.Final]
          at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76) ~[resteasy-client-4.6.0.Final.jar!/:4.6.0.Final]
          at com.sun.proxy.$Proxy88.remove(Unknown Source) ~[na:na]
          at de.adorsys.keycloak.config.repository.ClientScopeRepository.delete(ClientScopeRepository.java:86) ~[classes!/:3.1.2-rc0]
          at de.adorsys.keycloak.config.service.ClientScopeImportService.deleteClientScopesMissingInImport(ClientScopeImportService.java:100) ~[classes!/:3.1.2-rc0]
          at de.adorsys.keycloak.config.service.ClientScopeImportService.doImport(ClientScopeImportService.java:68) ~[classes!/:3.1.2-rc0]
          at de.adorsys.keycloak.config.service.RealmImportService.configureRealm(RealmImportService.java:176) ~[classes!/:3.1.2-rc0]
          at de.adorsys.keycloak.config.service.RealmImportService.updateRealm(RealmImportService.java:170) ~[classes!/:3.1.2-rc0]
          at de.adorsys.keycloak.config.service.RealmImportService.updateRealmIfNecessary(RealmImportService.java:142) ~[classes!/:3.1.2-rc0]
          at de.adorsys.keycloak.config.service.RealmImportService.doImport(RealmImportService.java:132) ~[classes!/:3.1.2-rc0]
          at de.adorsys.keycloak.config.KeycloakConfigRunner.run(KeycloakConfigRunner.java:71) ~[classes!/:3.1.2-rc0]
          at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:804) ~[spring-boot-2.4.3.jar!/:2.4.3]
          ... 13 common frames omitted
  ```
  </details>

**Expected behavior**
The `clientScope` should first be removed as reference in `defaultClientScopes` at the `client` and than be removed as `clientScope` in general.

**Possible issue?**
Order of removal is important. The reference to the scope first needs to be removed from the client before the scope itself can be removed.

**Environment:**
 - Keycloak Version: 12.0.4
 - keycloak-config-cli Version: v3.1.1-12.0.4
 - Java Version: 11.0.10+9

**Comment by jkroepke** [comment]
I guess its the same for `optionalClientScopes`, too.
