### ISSUE TITLE
Env Variable substitution is broken in 4.0.1*

### ISSUE THREAD

**Issue by thomasdarimont** [adorsys/keycloak-config-cli#455]
It seems as if the env variable substitution in keycloak-config-cli is broken since 4.0.1.

Env Variable references with defaults and without defaults are not resolved anymore.
Neither `sslRequired: ${env:SSL_REQUIRED:-EXTERNAL}` nor `sslRequired: ${env:SSL_REQUIRED}` in combination with `-e SSL_REQUIRED=ALL` works.

See the reproducer below:

Run Keycloak
```
docker run \
  --rm \
  -d \
  --name keycloak-bug \
  --net host \
  -e KEYCLOAK_USER=admin \
  -e KEYCLOAK_PASSWORD=admin \
   quay.io/keycloak/keycloak:14.0.0 \
  -b 0.0.0.0 \
  -bprivate 127.0.0.1
  ```

bug.yaml:
```
realm: demo
enabled: true
# env variable resolution is broken in 4.0.x
sslRequired: ${env:SSL_REQUIRED:-EXTERNAL}
```

```
#CLI_VERSION=v3.4.0-13.0.0
#CLI_VERSION=v4.0.1-13.0.1
CLI_VERSION=v4.0.1-14.0.0


docker run \
    -e KEYCLOAK_URL=http://localhost:8080/auth \
    -e KEYCLOAK_USER=admin \
    -e KEYCLOAK_PASSWORD=admin \
    -e KEYCLOAK_AVAILABILITYCHECK_ENABLED=true \
    -e KEYCLOAK_AVAILABILITYCHECK_TIMEOUT=120s \
    -e IMPORT_PATH=/config \
    -e IMPORT_FORCE=false \
    -e IMPORT_VARSUBSTITUTION=true \
    -e IMPORT_VARSUBSTITUTIONINVARIABLES=true \
    -v $(pwd)/bug.yaml:/config/bug.yaml:z \
    --rm \
    --net host \
    adorsys/keycloak-config-cli:$CLI_VERSION
```

keycloak-config-cli output CLI_VERSION=v3.4.0-13.0.0 works
```
2021-06-19 20:10:01.731  INFO 1 --- [           main] d.a.k.config.KeycloakConfigApplication   : Starting KeycloakConfigApplication v3.4.0 using Java 11.0.11 on gauss with PID 1 (/app/keycloak-config-cli.jar started by ? in /)
2021-06-19 20:10:01.734  INFO 1 --- [           main] d.a.k.config.KeycloakConfigApplication   : No active profile set, falling back to default profiles: default
2021-06-19 20:10:02.370  INFO 1 --- [           main] d.a.k.config.KeycloakConfigApplication   : Started KeycloakConfigApplication in 1.181 seconds (JVM running for 1.659)
2021-06-19 20:10:02.877  INFO 1 --- [           main] d.a.k.config.KeycloakConfigRunner        : Importing file '/config/bug.yaml'
2021-06-19 20:10:02.882  INFO 1 --- [           main] d.a.k.config.provider.KeycloakProvider   : Wait 120 seconds until http://localhost:8080/auth is available ...
2021-06-19 20:10:04.255  INFO 1 --- [           main] d.a.k.config.KeycloakConfigRunner        : keycloak-config-cli running in 00:01.549.
```

keycloak-config-cli output CLI_VERSION=v4.0.1-13.0.1 broken
```
2021-06-19 20:07:33.737  INFO 1 --- [           main] d.a.k.config.KeycloakConfigApplication   : Starting KeycloakConfigApplication v4.0.1 using Java 11.0.11 on gauss with PID 1 (/app/keycloak-config-cli.jar started by ? in /)
2021-06-19 20:07:33.740  INFO 1 --- [           main] d.a.k.config.KeycloakConfigApplication   : No active profile set, falling back to default profiles: default
2021-06-19 20:07:34.356  INFO 1 --- [           main] d.a.k.config.KeycloakConfigApplication   : Started KeycloakConfigApplication in 1.234 seconds (JVM running for 1.708)
2021-06-19 20:07:34.841  INFO 1 --- [           main] d.a.k.config.KeycloakConfigRunner        : Importing file '/config/bug.yaml'
2021-06-19 20:07:34.846  INFO 1 --- [           main] d.a.k.config.provider.KeycloakProvider   : Wait 120 seconds until http://localhost:8080/auth is available ...
2021-06-19 20:07:35.751 ERROR 1 --- [           main] d.a.k.config.KeycloakConfigRunner        : Cannot create realm 'demo': HTTP 500 Internal Server Error: {"error":"unknown_error"}
2021-06-19 20:07:35.751  INFO 1 --- [           main] d.a.k.config.KeycloakConfigRunner        : keycloak-config-cli running in 00:01.082.
```

Keycloak Error with Keycloak 14.0.0 and CLI_VERSION=v4.0.1-13.0.1 broken
``` 
20:07:35,722 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (default task-2) Uncaught server error: java.lang.IllegalArgumentException: No enum constant org.keycloak.common.enums.SslRequired.${ENV:SSL_REQUIRED:-EXTERNAL}
	at java.base/java.lang.Enum.valueOf(Enum.java:240)
	at org.keycloak.keycloak-common@14.0.0//org.keycloak.common.enums.SslRequired.valueOf(SslRequired.java:28)
	at org.keycloak.keycloak-server-spi-private@14.0.0//org.keycloak.models.utils.RepresentationToModel.importRealm(RepresentationToModel.java:265)
	at org.keycloak.keycloak-services@14.0.0//org.keycloak.services.managers.RealmManager.importRealm(RealmManager.java:557)
	at org.keycloak.keycloak-services@14.0.0//org.keycloak.services.managers.RealmManager.importRealm(RealmManager.java:495)
	at org.keycloak.keycloak-services@14.0.0//org.keycloak.services.resources.admin.RealmsAdminResource.importRealm(RealmsAdminResource.java:131)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
...
```

keycloak-config-cli output CLI_VERSION=v4.0.1-14.0.0 broken
```
2021-06-19 20:12:15.226  INFO 1 --- [           main] d.a.k.config.KeycloakConfigApplication   : Starting KeycloakConfigApplication v4.0.1 using Java 11.0.11 on gauss with PID 1 (/app/keycloak-config-cli.jar started by ? in /)
2021-06-19 20:12:15.229  INFO 1 --- [           main] d.a.k.config.KeycloakConfigApplication   : No active profile set, falling back to default profiles: default
2021-06-19 20:12:15.835  INFO 1 --- [           main] d.a.k.config.KeycloakConfigApplication   : Started KeycloakConfigApplication in 1.187 seconds (JVM running for 1.661)
2021-06-19 20:12:16.379  INFO 1 --- [           main] d.a.k.config.KeycloakConfigRunner        : Importing file '/config/bug.yaml'
2021-06-19 20:12:16.383  INFO 1 --- [           main] d.a.k.config.provider.KeycloakProvider   : Wait 120 seconds until http://localhost:8080/auth is available ...
2021-06-19 20:12:17.282 ERROR 1 --- [           main] d.a.k.config.KeycloakConfigRunner        : Cannot create realm 'demo': HTTP 500 Internal Server Error: {"error":"unknown_error"}
2021-06-19 20:12:17.283  INFO 1 --- [           main] d.a.k.config.KeycloakConfigRunner        : keycloak-config-cli running in 00:01.079.
```

Keycloak Error with Keycloak 14.0.0 and CLI_VERSION=v4.0.1-14.0.0 broken
``` 
same error as with v4.0.1-13.0.1
```

**Comment by thomasdarimont** [comment]
Okay I think I just hit this: https://github.com/adorsys/keycloak-config-cli/commit/aef6da540eb9d4bfd8807d44cddccd314a3b2eab :)

**Comment by jkroepke** [comment]
The change is document for 4.0.0, but I forgot them yesterday. Strictly a 5.0.0 version was required here to solve that correctly, but since the timeframe was small here, I put the breaking change in a patch level version.

Other option like move the tag and re-release the version 4.0.0 feels bad, too.

Btw. the syntax, use `$(var)` here instead `${}` comes from Kubernetes directly. 

https://kubernetes.io/docs/tasks/inject-data-application/define-interdependent-environment-variables/#define-an-environment-dependent-variable-for-a-container
