### ISSUE TITLE
wrong user updated when creating user with username equal to identity provider alias or some other resolved data

### ISSUE THREAD

**Issue by erkkikeranen** [adorsys/keycloak-config-cli#51]
I am using docker image adorsys/keycloak-config-cli:v0.8.0-7.0.0 and keycloak 7.0.0

This is the case:

I have an identity provider configured, which alias is **example**
I have user that is linked to this identityprovider, his username is **linkeduser**
Then I have a JSON file where I create a keycloak user whose name is **example**

The result is, that no user with the username **example** is created, 
but **linkeduser** is updated so that he receives the e-mail, names and roles that were meant for the username **example**

How is the user matched from the realm when deciding for updating or creating? 

```
...
2020-03-04 09:30:042020-03-04 08:30:04.709 DEBUG 177 --- [ main] d.a.k.config.service.UserImportService : Update user 'example' in realm 'my-realm'
```

JSON:

```
{
  "id": "my-realm",
  "realm": "my-realm",
  "users": [
    {
      "username": "example",
      "email": "example.user@example.com",
      "enabled": true,
      "firstName": "Example",
      "lastName": "User",
      "realmRoles": [
        "a_realm_role"
      ],
      "clientRoles": {
        "my-client": [
          "role_1",
          "role_2"
        ]
      },
      "credentials": [
        {
          "type": "password",
          "value": "password"
        }
      ]
    }
```

Update:

If i manually insert the user **example** and retry, I get 
HTTP 409 Conflict:

```
07:48:49
2020-03-04 08:48:49.263 DEBUG 186 --- [ main] d.a.k.config.service.UserImportService : Update user 'example' in realm 'my-realm'
07:48:49
2020-03-04 08:48:49.745 INFO 186 --- [ main] ConditionEvaluationReportLoggingListener :
07:48:49
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
07:48:49
2020-03-04 08:48:49.750 ERROR 186 --- [ main] o.s.boot.SpringApplication : Application run failed
07:48:49
java.lang.IllegalStateException: Failed to execute CommandLineRunner
07:48:49
at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:783) [spring-boot-2.1.7.RELEASE.jar!/:2.1.7.RELEASE]
07:48:49
at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:764) [spring-boot-2.1.7.RELEASE.jar!/:2.1.7.RELEASE]
07:48:49
at org.springframework.boot.SpringApplication.run(SpringApplication.java:319) [spring-boot-2.1.7.RELEASE.jar!/:2.1.7.RELEASE]
07:48:49
at org.springframework.boot.SpringApplication.run(SpringApplication.java:1214) [spring-boot-2.1.7.RELEASE.jar!/:2.1.7.RELEASE]

07:48:49
at org.springframework.boot.SpringApplication.run(SpringApplication.java:1203) [spring-boot-2.1.7.RELEASE.jar!/:2.1.7.RELEASE]
07:48:49
at de.adorsys.keycloak.config.Application.main(Application.java:9) [classes!/:0.8.0_2019-09-17 14:44:22]
07:48:49
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_222]
07:48:49
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_222]
07:48:49
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_222]
07:48:49
at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_222]
07:48:49
at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [keycloak-config-cli.jar:0.8.0_2019-09-17 14:44:22]
07:48:49
at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [keycloak-config-cli.jar:0.8.0_2019-09-17 14:44:22]
07:48:49
at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) [keycloak-config-cli.jar:0.8.0_2019-09-17 14:44:22]
07:48:49
at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52) [keycloak-config-cli.jar:0.8.0_2019-09-17 14:44:22]
07:48:49
Caused by: javax.ws.rs.ClientErrorException: HTTP 409 Conflict
07:48:49
at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.handleErrorStatus(ClientInvocation.java:216) ~[resteasy-client-3.0.14.Final.jar!/:3.0.14.Final]
07:48:49
at org.jboss.resteasy.client.jaxrs.internal.proxy.extractors.DefaultEntityExtractorFactory$3.extractEntity(DefaultEntityExtractorFactory.java:50) ~[resteasy-client-3.0.14.Final.jar!/:3.0.14.Final]
07:48:49
at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:104) ~[resteasy-client-3.0.14.Final.jar!/:3.0.14.Final]
07:48:49
at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:64) ~[resteasy-client-3.0.14.Final.jar!/:3.0.14.Final]
07:48:49
at com.sun.proxy.$Proxy91.update(Unknown Source) ~[na:na]
07:48:49
at de.adorsys.keycloak.config.repository.UserRepository.updateUser(UserRepository.java:65) ~[classes!/:0.8.0_2019-09-17 14:44:22]
07:48:49
at de.adorsys.keycloak.config.service.UserImportService$UserImport.updateUser(UserImportService.java:72) ~[classes!/:0.8.0_2019-09-17 14:44:22]
07:48:49
at de.adorsys.keycloak.config.service.UserImportService$UserImport.importUser(UserImportService.java:57) ~[classes!/:0.8.0_2019-09-17 14:44:22]
07:48:49
at de.adorsys.keycloak.config.service.UserImportService.importUser(UserImportService.java:39) ~[classes!/:0.8.0_2019-09-17 14:44:22]
07:48:49
at de.adorsys.keycloak.config.service.RealmImportService.importUsers(RealmImportService.java:170) ~[classes!/:0.8.0_2019-09-17 14:44:22]
07:48:49
at de.adorsys.keycloak.config.service.RealmImportService.updateRealm(RealmImportService.java:151) ~[classes!/:0.8.0_2019-09-17 14:44:22]
07:48:49
at de.adorsys.keycloak.config.service.RealmImportService.updateRealmIfNecessary(RealmImportService.java:133) ~[classes!/:0.8.0_2019-09-17 14:44:22]
07:48:49
at de.adorsys.keycloak.config.service.RealmImportService.doImport(RealmImportService.java:104) ~[classes!/:0.8.0_2019-09-17 14:44:22]
07:48:49
at de.adorsys.keycloak.config.KeycloakImportRunner.run(KeycloakImportRunner.java:35) ~[classes!/:0.8.0_2019-09-17 14:44:22]
07:48:49
at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:780) [spring-boot-2.1.7.RELEASE.jar!/:2.1.7.RELEASE]
07:48:49
... 13 common frames omitted

```

**Comment by erkkikeranen** [comment]
I inspected the keycloak documentation, and might it be possible that resolving if user exists is based on the generic search option, 

which matches "A String contained in username, first or last name, or email"

and thus the username for my test user was part of the email of another user. 

https://www.keycloak.org/docs-api/9.0/rest-api/index.html

I don't know if the Java API matches the rest-api, but could it be possible?

I'm not sure what is the actual conflict that is happening, what could it be?

**Comment by jkroepke** [comment]
Hi!

> I don't know if the Java API matches the rest-api, but could it be possible?

Jup, it looks like its also described at the keycloak-admin-cli help

```
/opt/jboss/keycloak/bin/kcadm.sh get  
Get all users whose 'username' matches '*test*' pattern, and 'email' matches '*@google.com*':
  $ kcadm.sh get users -r demorealm -q username=test -q email=@google.com

Note: it is the 'users' endpoint that interprets query parameters 'username', and 'email' in such a way that it results in the described semantics. Another endpoint may provide a different semantics.
```

Here is the reason:
https://github.com/keycloak/keycloak/blob/93a1374558643ee31e717c1dfacecb8ab8d95f68/model/jpa/src/main/java/org/keycloak/models/jpa/entities/UserEntity.java#L47


It means the keycloak-config-cli need to recheck if the username of the response is equal to the requested.

**Comment by erkkikeranen** [comment]
I believe this could be a valid solution, and relying on the exact username match would be clear. 

Is it possible that this improvement would be incorporated in the keycloak-config-cli?

**Comment by jkroepke** [comment]
Yes.
